name: Build and Test Client and Server

on:
  push:
    branches:
      - feature/US_#6
  pull_request:
    branches:
      - feature/US_#6

jobs:
  client-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Install dependencies for Angular client
        run: |
          cd client  # Ulazi u direktorijum gde se nalazi package.json
          npm install --legacy-peer-deps

      - name: Build Angular client
        run: |
          cd client  # Ponovno ulazi u direktorijum 'client'
          npm run build --prod

      - name: Test Angular client (optional)
        run: |
          cd client  # Ponovo ulazi u direktorijum 'client'
          npm run test -- --watch=false --browsers=ChromeHeadlessCI
