name: Build and Test Django Server

on:
  push:
    branches:
      - feature/US_#6
  pull_request:
    branches:
      - feature/US_#6

jobs:
  server-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      - name: Install dependencies for Django server
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set environment to test
        run: |
          echo "DJANGO_ENV=test" >> $GITHUB_ENV

      - name: Load environment variables from .env.test
        run: |
          set -o allexport
          source $GITHUB_WORKSPACE/server/.env.test
          set +o allexport

      - name: Check if .env.test exists (debug)
        run: |
          ls -alh $GITHUB_WORKSPACE/server/
          cat $GITHUB_WORKSPACE/server/.env.test

      - name: Run Django migrations and tests with SQLite
        run: |
          cd server
          source venv/bin/activate
          python manage.py migrate
          python manage.py test
