name: Build Django (server)

on:
  push:
    branches:
      - feature/US_#6
  pull_request:
    branches:
      - feature/US_#6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run migrations
        run: |
          cd server
          python manage.py migrate

      - name: Run Django tests
        run: |
          cd server
          python manage.py test
